// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Erivan Ferreira",
            "email": "erivan.c39@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Lol Player Finder",
	Description:      "APi to find League of Legends Players",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
//	RightDelim:       "}}",
//	LeftDelim:        "{{",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
