definitions:
  appError.AppError:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  types.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      gameName:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: erivan.c39@gmail.com
    name: Erivan Ferreira
  description: API to find League of Legends Players according to their roles and
    championms
  title: Lol Player Finder
  version: "0.1"
paths:
  /user:
    get:
      description: Get all accounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.User'
            type: array
      summary: Get accounts
    post:
      consumes:
      - application/json
      description: Create a new account
      parameters:
      - description: Your name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Your email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Your password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: In game name
        in: body
        name: gameName
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/appError.AppError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/appError.AppError'
      summary: Create account
  /user/{id}:
    delete:
      description: Delete one account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/appError.AppError'
      summary: Delete account
    get:
      description: Get one account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
      summary: Get account
    patch:
      consumes:
      - application/json
      description: Update account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: New name
        in: body
        name: name
        schema:
          type: string
      - description: New password
        in: body
        name: password
        schema:
          type: string
      - description: New in game name
        in: body
        name: gameName
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/appError.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/appError.AppError'
      summary: Update account
swagger: "2.0"
